name = "pnwsauna"
compatibility_date = "2024-02-01"

[site]
bucket = "./out"

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "18"
NEXT_TELEMETRY_DISABLED = "1"

[[build.upload]]
type = "directory"
directory = ".next"
site = "pnwsauna" 